plugins.json

The [nf-validation plugin](https://github.com/nextflow-io/nf-validation) validates nextflow pipeline parameters using a JSON Schema.
1. You can find an [example JSON](https://github.com/nextflow-io/nf-validation/blob/master/plugins/nf-validation/src/testResources/nextflow_schema.json) Schema in the plugin docs.
2. Include and execute the function into a pipeline with some parameters: 
```
include { validateParameters } from 'plugin/nf-validation'
params.input = 'test_input.csv'
params.outdir = 'testDir'
params.xyz = '/some/path'
workflow {
validateParameters('path/to/nextflow_schema.json')
}
```
The validation should fail if the input file is not found and xyz is an unknown parameter.
Another functionality is to validate an input samplesheet and generate a channel.
1. You can find an …

add nf-validation 0.1.0

---

.github/schema.json
.github/workflows/validate-plugins.yaml
.prettierrc

Should run on push and pull-request events and throw an error if there's something wrong in the file contents.
Also added a config for [Prettier](https://prettier.io/), but no GitHub action workflow to enforce that (yet).

Add JSON schema + GitHub Actions workflow to validate

---

plugins.json

Update nf-jarvice to 0.7.0 with better error handling.

Update nf-jarvice to 0.7.0

---

plugins.json

Fixes a small bug with the immutable meta handling

add nf-validation 0.2.1

---

plugins.json

This release improves stability and contains bugfixes.

Release nf-cws v1.0.2

---

plugins.json

What's Changed
* [GH-56] add `timeFactor` in float conf. by @jealous in https://github.com/MemVerge/nf-float/pull/57
* Refresh the workDir if not empty. by @jealous in https://github.com/MemVerge/nf-float/pull/58
**Full Changelog**: https://github.com/MemVerge/nf-float/compare/0.3.0...v0.3.1

Update nf-float 0.3.1

---

plugins.json

@ewels can you use your god powers on this :pleading_face: ?

Add nf-validation 0.3.2

---

plugins.json

Enable to run scheduler in external environment

Added nf-cws version v1.0.3

---

plugins.json

Reverts nextflow-io/plugins#39

Revert "add nf-validation 0.3.4"

---

plugins.json

nf-quilt@0.7.0

---

plugins.json

Find even in deeply-nested subfolders

v0.7.5 - auto-detect mulitqc_report.html

---

plugins.json

@ewels I once again summon you and your god powers to please merge this PR :smile:

nf-validation v1.1.2

---

plugins.json

What's Changed:
* Add project name in the MMC job tags.

Upgrade nf-float plugin to 0.4.1

---

plugins.json

https://github.com/bentsherman/nf-boost

nf-boost 0.1.0, 0.2.0

---

plugins.json

@ewels it's been a while but I'd like to summon your god powers to approve and merge this PR :pleading_face:

Add nf-schema 2.1.0

---

plugins.json

Add the latest version of `nf-quilt`.

Add nf-quilt@0.8.6

---

plugins.json

@ewels can you take a look at this real quick please? :p

nf-schema v2.1.1

---

plugins.json

Hi team 👋 
Adding another release for the `nf-nomad` plugin for your consideration.
CC @tomiles @jagedn

Add JSON snippet for latest nf-nomad release

---

plugins.json

Running nextflow against Snowflake SnowparkContainerService

release nf-snowflake 0.6.0

---

plugins.json

Changelog: https://github.com/nextflow-io/nf-schema/releases/tag/2.2.0

nf-schema v2.2.0

---

plugins.json

Hi team 👋 
Here's another PR for the latest `nf-nomad` release!

Add nf-nomad v0.3.1

---

plugins.json

Changelog: https://github.com/nextflow-io/nf-schema/releases/tag/2.2.1

nf-schema v2.2.1

---

plugins.json

I would like to include last/first version of nf-parquet in the list

v0.2.0 nf-parquet

---

plugins.json

fix bugs of cancel shutdown cos client in multipartCopyObject, which cause http pool shutdown

feat(nf-tencentcloud): release 1.0.1 and 2.0.1

---

plugins.json

Changelog: https://github.com/nextflow-io/nf-schema/releases/tag/2.3.0

nf-schema v2.3.0

---

plugins.json

I would like to publish the release 1.0.0 of nf-pgcache

nf-pgcache release 1.0.0

---

plugins.json

Changelog:
- Updated to new Nextflow Pod Naming Schema
- Updated dependencies to work with newer Nextflow versions (based on nf-hello)

Added nf-cws version v1.0.6

---

plugins.json

I am excited to share that after 3 years of hard and continuous work, Location Aware Scheduling for Nextflow is available via this plugin.
For more details, I refer to our paper: [WOW: Workflow-Aware Data Movement and Task Scheduling for Dynamic Scientific Workflows](https://arxiv.org/pdf/2503.13072.pdf)
With WOW, we could reduce the makespan for RNA-Seq by 18% (against Ceph), 53% (compared to NFS), and 95% for I/O intensive task chaining.
Please merge.

Added nf-cws version v2.0.0

---

plugins.json

nf-cws 2.0.1

---

plugins.json

Adds the nf-fovus plugin to the Nextflow plugin registry.
nf-fovus is designed to support workload configuration and optimization through custom constraint evaluation and job configuration logic. It provides flexible modeling for both containerized and monolithic environments and supports advanced resource and licensing strategies.
Key Features
- Supports hybrid workload definitions (monolithic + containerized).
- Includes CPU/GPU constraint models and license-aware scheduling.
- Easily configurable via JSON or DSL extensions.
README: [https://github.com/Fovus/nf-fovus#](https://github.com/Fovus/nf-fovus#)

Add new nf-fovus plugin
