nextflow-io/plugins

plugins.json
I wish to publish the latest version of nf-prov so others can start playing around with the plugin. My only question is whether I can specify an edge release as the minimum Nextflow version. If so, this PR should be good to go!
=> Publish nf-prov version 1.0.0

plugins.json
[0.3.3] 2023-03-08
- Fail gracefully on quilt3 errors
- Detailed NextFlow Tower instructions
- Call quilt3 during integration tests
- Add full Quilt+ URL support, including metadata in query string
=> nf-quilt 0.3.3

plugins.json
Dear Nextflow team,
I am trying to do a full validation before submitting the plugin to you, so this PR is a Draft for now.
To do so, I tried to hardcode a different plugins.json url into nextflow to use a forked version of yours and so be able to emulate what would happen.
But I fail to do so 😕
Changes I made are the following:
```
diff --git a/modules/nf-commons/src/main/nextflow/plugin/Plugins.groovy b/modules/nf-commons/src/main/nextflow/plugin/Plugins.groovy
index 0ed48a86a..6e81b2f70 100644
--- a/modules/nf-commons/src/main/nextflow/plugin/Plugins.groovy
+++ b/modules/nf-commons/src/main/nextflow/plugin/Plugins.groovy
@@ -31,7 +31,7 @@ import org.pf4j.PluginManager
@CompileStatic
class Plugins {
-    public static final String DEFAULT_PLUGINS_REPO = …
```
=> Feat: Add experimental support for Jarvice plugin

plugins.json
The nf-float plugin add a `FloatGridExecutor` to allow Nextflow to use MemVerge Memory Machine Cloud as backend.
The project's source code is available at:
https://github.com/MemVerge/nf-float/
=> Add nf-float plugin release 0.1.7

plugins.json
- automatically use the latest version of the Kubernetes Scheduler Docker Image [[commit](https://github.com/CommonWorkflowScheduler/nf-cws/commit/da42dfcafed7f7c97490b14a99999922545ed1f3)]
- allow to submit additionally arguments to the Common Workflow Scheduler Interface [[commit](https://github.com/CommonWorkflowScheduler/nf-cws/commit/5e38d980fcbd088d606c7a07f5bdfa46b98e7eb1)]
=> Update nf-cws to  v1.0.1

plugins.json
Release 0.1.8 includes multiple bugfixes:
* [GH-20] Update project's org. name. by @jealous in https://github.com/MemVerge/nf-float/pull/21
* [GH-22] Include auto-install in the document by @jealous in https://github.com/MemVerge/nf-float/pull/23
* [GH-26] Support config in process. by @jealous in https://github.com/MemVerge/nf-float/pull/33
* [GH-32] Upload bin directory. by @jealous in https://github.com/MemVerge/nf-float/pull/34
* [GH-28] Correct syntax in README. by @jealous in https://github.com/MemVerge/nf-float/pull/36
* [GH-29] Read credentials from ENV or secrets. by @jealous in https://github.com/MemVerge/nf-float/pull/35
* [GH-38] Track job with tags by @jealous in https://github.com/MemVerge/nf-float/pull/39
* [GH-37] Support default registry. by @jealous in …
=> Add nf-float release 0.1.8

plugins.json
This release includes the fix for:
* [GH-25](https://github.com/MemVerge/nf-float/issues/25) Simplify the use of S3 bucket for work directory.
* [GH-41](https://github.com/MemVerge/nf-float/issues/41) Incorrect parsing of process and float scope.
Now user could use s3 work directory to start a workflow on their laptop without mounting a NFS.
Cleanup the configuration settings for nf-float
* Use `float` scope for:
* `address` - op-center address
* `username` - op-center username
* `password` - op-center password
* `nfs` - optional, the nfs work directory
* Use `process` scope for:
* `cpus` - the default CPU cores of the worker
* `memory` - the default memory size of the worker
* `container` - the default container image of the task
* `executor` - default executor of the task
=> Update nf-float release 0.2.0

plugins.json
Note that the last couple versions were not formally published, as they were used for private testing
=> nf-quilt 0.4.3: only publish on success, customize README

plugins.json
* What's Changed
* Add Fusion support by @jealous in https://github.com/MemVerge/nf-float/pull/48
* Add support for several process directives by @bentsherman in https://github.com/MemVerge/nf-float/pull/51
* [GH-50] Input or output on s3 is not available. by @jealous in https://github.com/MemVerge/nf-float/pull/52
* Upgrade version to 0.3.0 by @jealous in https://github.com/MemVerge/nf-float/pull/53
* [GH-54] Support `extraOptions` of float by @jealous in https://github.com/MemVerge/nf-float/pull/55
* New Contributors
* @bentsherman made their first contribution in https://github.com/MemVerge/nf-float/pull/51
Full Changelog: https://github.com/MemVerge/nf-float/compare/0.2.0...v0.3.0
=> Add nf-float release 0.3.0

plugins.json
nf-quilt [0.4.4] 2023-08-22
- JDK 11 compatibility (i.e., remove stripIndent)
- Add parameter to skip README and metadata (default is to include both)
- Improve test coverage of metadata and QuiltProduct
=> nf-quilt 0.4.4

plugins.json
- fix metadata in README.md
- write out nf-quilt/*.json files
- add summarize wildcards (md, html) for QuiltProduct
- redo normalizedPaths
- reduce logging (especially stack traces and filesystem calls)
- convert non-fatal errors to warnings
=> nf-quilt 0.4.5

plugins.json
* Report RC code when MMC returns error. by @jealous in https://github.com/MemVerge/nf-float/pull/59
* Download float cli from op-center. by @jealous in https://github.com/MemVerge/nf-float/pull/60
* Try the best to fix s3 options. by @jealous in https://github.com/MemVerge/nf-float/pull/61
* sync the float binary. by @jealous in https://github.com/MemVerge/nf-float/pull/62
* Add multiple enhancements. by @jealous in https://github.com/MemVerge/nf-float/pull/64
* Allow user to omit credentials. by @jealous in https://github.com/MemVerge/nf-float/pull/65
* Trim extra characters in image. by @jealous in https://github.com/MemVerge/nf-float/pull/66
* Add max cpu and memory factor support. by @jealous in https://github.com/MemVerge/nf-float/pull/67
* Add job kind tag to identify the kind of …
=> Update nf-float plugin to 0.4.0

plugins.json
This will ensure we automatically (and correctly) display mutliqc/multiqc_report.html in the Quilt Catalog,
which helps with the proposed Gallery.
=> Fix auto-detection of multiqc files

plugins.json
Changes:
- do not start a pod if a URL is specified
- Prepare for online memory request predictions in CWS
- Support Java 21
=> Added nf-cws version v1.0.4

plugins.json
Hello Nextflow community and Seqera!
I've written a small plugin that helps in complex containerized Nextflow projects where a GitHub repository may be orchestrated (build and publish) with Docker Compose and all container version labels are stored in the [dotenv](https://hexdocs.pm/dotenvy/dotenv-file-format.html) file ([relevant Docker Compose docs](https://docs.docker.com/compose/environment-variables/set-environment-variables/)).
To reduce duplication of setting container versions in both a dotenv file and also again in Nextflow configuration (and risk them going out of sync), this plugin can be used to automatically pull those versions from the dotenv file into the Nextflow scope using an importable function.
The upstream repository is here:
- …
=> Add the plugin nf-dotenv from @fulcrumgenomics

plugins.json
**Name:** nf-iridanext
**Repository:** https://github.com/phac-nml/nf-iridanext
This plugin adds some pre-processing and post-processing tasks that will be useful for us to integrate Nextflow pipelines within our larger system (called [IRIDA Next](https://github.com/phac-nml/irida-next)) for managing microbial genomics data and analysis results. In particular, the main post-processing task is to create a JSON file containing output files from a Nextflow pipeline plus contextual metadata for loading into our system.
As an example, this plugin would allow the following Nextflow configuration to be used to create the below JSON output (more examples on https://github.com/phac-nml/nf-iridanext):
**nextflow.config**
```nextflow
iridanext {
enabled = true
output {
path = …
```
=> Added nf-iridanext 0.1.0

plugins.json
* Properly read input path URIs (auto-install)
* Support array metadata
* Better debugging and error reporting (fewer silent failures)
=> nf-quilt 0.7.9

plugins.json
Version 1.0.1 of the YellowDog Plugin fixes a potential race condition when creating new task groups for task submissions.
=> nf-yellowdog 1.0.1

plugins.json
Hi dear @pditommaso ,
Happy to share the first public release of `nf-nomad` plugin in this index.
With this release we do consider the plugin to be in a usable format but since the nomad executor (much like Kubernetes) can be configured differently, the plugin will grow as per the user requests and our own experiences.
Big thanks to @jagedn, @tomiles, @jhaezebr and @matthdsm for the collaboration on this plugin and setting up the (internal) testing infrastructure and _especially_ for keeping the momentum going! 🙏 😊 💯
=> First release of nf-nomad plugin

plugins.json
This PR builds upon #76 and address the issue identified by @jagedn 
```
Downloading plugin nf-nomad@0.1.0
ERROR ~ SHA512 checksum of downloaded file nf-nomad-0.1.0.zip does not match that from plugin descriptor. Got 9e59d60ffa925f1e63b8e79c1ecced80ea754eb06014fc3b5f8008d457368ea8568df87304beb4d3038dc09a0bc92a3517980d22014318cbd9f39f5a661d551e but expected 34a1ab68478acd5b8d816517bd8f5fd67fee858ed01da0ce24ea7b8eca6aaab5909fd6e5cccf1c5ce7ca78b01b4c33cf3402935a1a88c2c68dfa210e503f1da0
```
=> Fix the SHA sum for nf-nomad

plugins.json
Hi team,
Here's the PR for updating a new version of the nf-nomad plugin 
https://github.com/nextflow-io/nf-nomad/releases/tag/0.1.1
=> Add nf-nomad v0.1.1 to the index

plugins.json
This version supports the newest feature of the Common Workflow Scheduler to size task's memory dynamically.
=> Added nf-cws version v1.0.5

plugins.json
The new version contains a bugfix that disable rerun on checkpoint restore failure at the MMC side.  We will use the Nextflow's re-run mechanism when error happens.  Because Nextflow will create a new work directory for the re-run task and won't have any dirty files of the previous failed run.
Related issue: https://github.com/MemVerge/nf-float/issues/72
Related PR: https://github.com/MemVerge/nf-float/pull/73
=> Added nf-flaot version v0.4.2

plugins.json
Hi team,
Adding the latest iteration of the nf-nomad plugin.
The release notes are mentioned here https://github.com/nextflow-io/nf-nomad/releases/tag/0.1.2
=> Add new release for nf-nomad 0.1.2 release

plugins.json
Upgrade nf-float plugin to 0.4.3. This version includes a fix that sometimes the job status in MMC is not updated to Nextflow properly.
The root cause is that we depend on a full job list for individual job status update.  But sometimes the full poll doesn't take place or doesn't finish in time.
The fix is to create the status entry for each job in the plugin right after we submit a job to MMC.
Regression test has been run with nf-core/rnaseq test profile on MMC.
The change is available at:
https://github.com/MemVerge/nf-float/pull/74
=> Add nf-float v0.4.3

plugins.json
nf-tencentcloud is a nextflow plugin designed to add Tencent Cloud Object storage and Tencent Healthcare Omics Platform executor adaptation support to the nextflow workflow engine.
Its design goal is to extend Tencent Cloud's native support for Nextflow workflows, allowing users to run Nextflow workflows using Tencent Cloud resources in a simple and easy-to-use manner.
=> feat(nf-tencentcloud): first commit of adding nf-tencentcloud plugin

plugins.json
This release includes the support for the `scratch` option. For s3 storage, allow the user to authorize with session token. It also includes several bugfixes. See the details below.
What's Changed:
* [GH-75](https://github.com/MemVerge/nf-float/issues/75) Too many `put xxx into map` log by @jealous in https://github.com/MemVerge/nf-float/pull/76
* [GH-77](https://github.com/MemVerge/nf-float/issues/77) Support s3 token authorization by @jealous in https://github.com/MemVerge/nf-float/pull/78
* [GH-77](https://github.com/MemVerge/nf-float/issues/77) Update the readme for s3 token by @jealous in https://github.com/MemVerge/nf-float/pull/79
* [GH-69](https://github.com/MemVerge/nf-float/issues/69) Support `float` in `ext` directive`. by @jealous in …
=> Add nf-float 0.4.4

plugins.json
Fixing a compatibility issue between MMC and AWS API. The endpoint for AWS region us-east-1 is different with other regions.  The algorithm used by MMC to provide the default endpoint does not work.
Add support in nf-float plugin to retrieve the endpoint configuration from `aws.client.endpoint` and supply this to MMC if available.
Do not change the default `scratch` option if user has local work dir.
Changes are available at:
https://github.com/MemVerge/nf-float/pull/94
https://github.com/MemVerge/nf-float/pull/95
=> Add nf-float 0.4.5

plugins.json
This release fix an issue that the library path of aws cli affect other user applications, such as gzip.  See details below:
* [FLOAT-4537](https://github.com/MemVerge/nf-float/pull/98) Failed to execute user binary.
* [GH-99](https://github.com/MemVerge/nf-float/pull/99) Add volume size for default scratch option.
Release page:
[nf-float 0.4.6 release](https://github.com/MemVerge/nf-float/releases/tag/0.4.6)
=> Add nf-float 0.4.6

plugins.json
- Supports (only) Nextflow 24.10 and later (uses Groovy 4)
- Shift to quiltcore 0.1.6+ convenience methods
- Shift metadata and configuration to `quilt` scope of nextflow.config
- Moved test workflows into `wf` folder
- Write the output URI when publishing
- Improve handling of dynamically-specified URIs
- Rewrite README.md, splitting out developer documentation to README_DEV.md
=> nf-quilt v0.9.1

plugins.json
I would like to add a new plugin, nf-pgcache who use a postgresql instance to manage tasks cache
=> add new nf-pgcache

plugins.json
- Plot co2e and energy in one plot with two axis.
- Report nf-co2footprint version in `co2footprint_report_*.html` and `co2footprint_summary_*.txt` reports.
- Show Plugin parameters in html and text reports.
- Show CO2 equivalences using scientific annotations in the html reports.
- Show CO2 equivalences in text reports.
- Updated documentation.
=> nf-co2footprint version 1.0.0-beta.1 added

plugins.json
**Name**: nf-iridanext
**Repository**: https://github.com/phac-nml/nf-iridanext
**Version**: 0.3.0
This update adds functionality to the `nf-iridanext` plugin to allow for manual loading of sample IDs in addition to automatic detection. Certain Nextflow workflow design patterns require the ability to load these IDs manually, otherwise these IDs are unknown to the plugin, and the automatic generation of certain [IRIDA Next](https://github.com/phac-nml/irida-next)-required files cannot be completed.
Additional test cases and documentation have also been added.
=> Adding nf-iridanext 0.3.0

plugins.json
1. Added a new configuration option: `validation.maxErrValSize` which sets the maximum length that a value in an error message can be. The default is set to 150 characters.
2. Added a new function: `validate()` that can be used to validate any data structure using a JSON schema.
1. Move the unpinned version check to an observer. This makes sure the warning is always shown and not only when importing a function.
2. Added a missing inherited method to the observer to fix issues with workflow output publishing
3. Fixed unexpected failures with samplesheet schemas using `anyOf`, `allOf` and `oneOf`
4. Fixed an error with help messages when the `type` keyword was missing
5. Fix compilation errors in Java 21
1. Slow uniqueness check (> 2hrs for 100k samples) made 400x faster by switching from …
=> Add nf-schema 2.4.0

plugins.json
1. Allow `GString` values for all configuration options that allow `String` values.
=> Add nf-schema 2.4.1

plugins.json
This plugin visualizes and traces the physical DAG in Nextflow pipelines. It provides insights into data flow, process dependencies, and file sizes. I’d love to share this with the community!
=> Added nf-datatrail version 0.0.1

README.md, plugins.json
Information on how to use nf-lamin: https://github.com/laminlabs/nf-lamin
Road map: https://github.com/laminlabs/nf-lamin/issues/48
=> Add entry for nf-lamin@0.0.1

plugins.json
Hello Nextflow community and Seqera!
I've written a small plugin that exposes some useful functions and factory methods using dataclasses in [`fgbio`](https://github.com/fulcrumgenomics/nf-fgbio). 
In particular, two such methods have been initially implemented:
1. We often pass in [Read Structures](https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures) as a parameter or metadata on samples to pipelines, and the `readStructure` method will return a [`ReadStructure`](https://www.javadoc.io/doc/com.fulcrumgenomics/fgbio_2.13/latest/com/fulcrumgenomics/util/ReadStructure.html) object, which is really useful in itself, but it does parsing and yields better error messages when the read structure is invalid (see an [online validator](https://fulcrumgenomics.github.io/fgbio/validate-read- …
=> Add the plugin nf-fgbio from @fulcrumgenomics

plugins.json
Nextflow plugin for MemVerge Memory Machine Cloud
- Added examples for extra/commonExtra
- Fixed an issue where an unusual Memory/CPU ratio caused the task submission to fail
Thank you!
=> Added release 0.4.7 for nf-float

plugins.json
[project here with some documentation](https://github.com/royjacobson/nf-python/)
=> Add new plugin nf-python 

plugins.json
1. Added a new configuration option: `validation.help.enumLength` which sets the maximum length of enum values in the help message. The default is set to the value in the `COLUMNS` environment variable or 100 character if that variable isn't set.
2. Added top-level schema description for detailed help `--help <args>`. If `<args>` is associated with a schema, then the top-level fields will be shown similarly to `--help` for the main schema.
3. Added a Troubleshooting and FAQ page to the documentation.
1. The plugin now properly validates cloud storage files instead of skipping them. Exotic errors will be added to the error messages instead of failing the validation outright.
2. Migrated to the new observer class in Nextflow 25.04.0
3. Rework the deprecated `paramsHelp()` function to allow …
=> Add new version 2.5.0 of nf-schema plugin
